import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <p className='m-auto mt-1 inline-block rounded border border-red-800 bg-red-300 p-3 text-4xl hover:bg-slate-500'>
          Template
        </p>
      </main>
    </div>
  )
}

export default Home
